packages:
  - 'common/*'
  - 'services/*/asr-api'
  - 'services/*/asr-server'
  - 'services/*/translate-api'
  - 'services/*/translate-server'
  - 'gateway/*'
  - 'auth/*'
  - 'components/*'
  - '!components/desktop-lyrics'
